#%RAML 1.0 NamedExample

value:
  id: "123"
  firstName: "Gabbar"
  lastName: "Singh"
  address: "Ramgarh ke jungle"
  postal: "RKJ"
  country: "India"
  miles: 50
  creationDate: "2010-02-28T16:41:41.090Z" 
  accountType: "Sardaar"