#%RAML 1.0 NamedExample

value:
  - 
    firstName: "Gabbar"
    lastName: "Singh"
    address: "Ramgarh ke jungle"
    postal: "RKJ"
    country: "India"
    miles: 50
    accountType: "Sardaar"
  - 
    firstName: "Kalia"
    lastName: "Jagga"
    address: "Ramgarh ke jungle"
    postal: "RKJ"
    country: "India"
    miles: 10
    accountType: "Lutera"